language: ruby
rvm:
  - 2.3.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  ssh_known_hosts: tin.fyi
before_install:
  - bash _scripts/install.sh
script:
  - bash _scripts/build.sh
#  - bash _scripts/test.sh
after_success:
  - bash _scripts/deploy.sh
